{
 "title": "Manta-Monitor-Buckets",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Retries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retry Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_retries_mean_rate",
       "legendFormat": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests-Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_requests_get_99thPercentile",
       "legendFormat": "99th"
      },
      {
       "expr": "manta_monitor_buckets_requests_get_75thPercentile",
       "legendFormat": "75th"
      },
      {
       "expr": "manta_monitor_buckets_requests_get_50thPercentile",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Throughput - Last 1 minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_requests_get_OneMinuteRate",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests-Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_requests_delete_99thPercentile",
       "legendFormat": "99th"
      },
      {
       "expr": "manta_monitor_buckets_requests_delete_75thPercentile",
       "legendFormat": "75th"
      },
      {
       "expr": "manta_monitor_buckets_requests_delete_50thPercentile",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Throughput - Last 1 minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_requests_delete_OneMinuteRate",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SocketTimeoutException Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_buckets_exceptions_socket_time_out_FiveMinuteRate",
       "legendFormat": "FiveMinuteRate"
      }
     ]
    },
    {
     "title": "Rate of Increase in SocketTimeoutException",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(manta_monitor_buckets_exceptions_socket_time_out_count [1m])"
      }
     ]
    }
   ]
  },
  { "title": "Requests-Put", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "manta_monitor_buckets_requests_put_99thPercentile",
     "legendFormat": "99th"
    },
    {
     "expr": "manta_monitor_buckets_requests_put_75thPercentile",
     "legendFormat": "75th"
    },
    {
     "expr": "manta_monitor_buckets_requests_put_50thPercentile",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Throughput - Last 1 minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "manta_monitor_buckets_requests_put_OneMinuteRate",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Manta Monitor Put Request Latency - P99",
   "type": "graph",
   "description": "This is the request latency observed by the manta-monitor application and not what is reported by the manta client. The values observed includes the time taken to create a bucket and put an object into it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(manta_monitor_buckets_put_request_latency_FileUploadGetDeleteChain_bucket [1m]))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Average Put Request Latency",
   "type": "graph",
   "description": "The average put request latency as observed by manta-monitor, that includes the time taken to create a bucket and upload an object.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(manta_monitor_buckets_put_request_latency_FileUploadGetDeleteChain_sum [1m])/rate(manta_monitor_buckets_put_request_latency_FileUploadGetDeleteChain_count [1m])",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}