{
 "title": "Manta-Monitor-Dir",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Retries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Retry Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "manta_monitor_dir_retries_mean_rate",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Requests-Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_get_99thPercentile",
       "legendFormat": "99th"
      },
      {
       "expr": "manta_monitor_dir_requests_get_75thPercentile",
       "legendFormat": "75th"
      },
      {
       "expr": "manta_monitor_dir_requests_get_50thPercentile",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Throughput - Last 1 minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_get_OneMinuteRate",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests-Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_delete_99thPercentile",
       "legendFormat": "99th"
      },
      {
       "expr": "manta_monitor_dir_requests_delete_75thPercentile",
       "legendFormat": "75th"
      },
      {
       "expr": "manta_monitor_dir_requests_delete_50thPercentile",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Throughput - Last 1 minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_delete_OneMinuteRate",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "SocketTimeoutException Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_exceptions_socket_time_out_FiveMinuteRate",
       "legendFormat": "FiveMinuteRate"
      }
     ]
    },
    {
     "title": "Rate of Increase in SocketTimeoutException",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(manta_monitor_dir_exceptions_socket_time_out_count [1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests-Put",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_put_99thPercentile",
       "legendFormat": "99th"
      },
      {
       "expr": "manta_monitor_dir_requests_put_75thPercentile",
       "legendFormat": "75th"
      },
      {
       "expr": "manta_monitor_dir_requests_put_50thPercentile",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Throughput - Last 1 minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "manta_monitor_dir_requests_put_OneMinuteRate",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "Average Put Request Latency",
     "type": "graph",
     "description": "The average put request latency as observed by manta-monitor, that includes the time taken to create a directory and upload an object.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(manta_monitor_dir_put_request_latency_FileUploadGetDeleteChain_sum [1m])/rate(manta_monitor_dir_put_request_latency_FileUploadGetDeleteChain_count [1m])",
       "legendFormat": "Latency"
      }
     ]
    }
   ]
  }
 ]
}